name: pre-commit

on: [push]

env:
  PYTHON_VERSION: 3.10.13

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: "${{ env.PYTHON_VERSION }}"

    - uses: pre-commit/action@v3.0.0
      env:
        SKIP: pyright,codespell,isort,black,flake8,bandit
